### ISSUE TITLE
CSS imported assets are bundled twice

### ISSUE THREAD

**Issue by Atmos4** [rspack-contrib/storybook-rsbuild#66]
When importing assets in CSS, it gets bundled twice (once by Storybook and once by rsbuild) resulting in broken URLs.

Example repo: https://github.com/Atmos4/rsbuild-storybook-demo/tree/wrong-asset-import
Branch: `wrong-asset-import`

Example CSS:
```css
.asset-in-css::after {
  content: url("./assets/context.png");
  width: 10px;
  height: 10px;
}
```

Resulting in the following URL: `/static/css/async/static/image/static/media/src/stories/assets/context.png`.
The correct URL (that resolves to something) is: ` /static/image/static/media/src/stories/assets/context.png`

Expected behavior:

Storybook should ignore those assets. Maybe there is a configuration option I can tweak to make storybook ignore these CSS assets, I am not sure.
