### ISSUE TITLE
Asset loading in CSS doesn't work in dev

### ISSUE THREAD

**Issue by Atmos4** [rspack-contrib/storybook-rsbuild#72]
_Note: this is just me reopening #66 with more details_

## Problem
When trying to load assets in CSS with a default storybook configuration, it doesn't work in dev and will not load the asset properly.

Example repo: https://github.com/Atmos4/rsbuild-storybook-demo/tree/css-asset-loading-not-working
branch `css-asset-loading-not-working`

Example code:
```css
.asset-in-css::after {
  content: url("./assets/context.png"); /* <-- this asset will not load in dev */
  width: 10px;
  height: 10px;
}
```

## Temporary solution

Add this to `.storybook/main.ts`
```ts
export default {
  ... your config
  rsbuildFinal: (config) => {
    config.output ||= {};
    config.output.distPath = {
      image: ".",
      font: ".",
      svg: ".",
    };
    return config;
  },
} satisfies StorybookConfig;
```
